var quotes = [
    "'I’m Commander Shepard, and this is my favorite store on the Citadel!' – Mass Effect 2",
    "'It’s time to kick ass and chew bubble gum…and I’m all outta gum.' – Duke Nukem",
    "'What is a man? A Miserable little pile of secrets!' – Castlevania: Symphony of the Night",
    "'We’re not tools of the government or anyone else. Fighting was the only thing I was good at, but at least I always fought for what I believed in.'– Metal Gear Solid",
    "'They were all dead. The final gunshot was an exclamation mark to everything that had led to this point. I released my finger from the trigger. And then it was over.' – Max Payne",
    "'The sun went down with practiced bravado. Twilight crawled across the sky, laden with foreboding. I didn’t like the way the show started. But they had given me the best seat in the house. Front row center.' – Max Payne",
    "'The right man in the wrong place can make all the difference in the world.' – Half-Life 2",
    "'FINISH HIM!' – Mortal Kombat",
    "'Would you kindly…' – Bioshock",
    "'The healthy human mind doesn’t wake up in the morning thinking this is its last day on Earth. But I think that’s a luxury, not a curse. To know you’re close to the end is a kind of freedom. Good time to take… inventory.' – Call of Duty: Modern Warfare",
    "'Some trees flourish, others die. Some cattle grow strong, others are taken by wolves. Some men are born rich enough and dumb enough to enjoy their lives. Ain’t nothing fair.' – Red Dead Redemption",
    "'You can’t break a man the way you break a dog or a horse. The harder you beat a man, the taller he stands.' – Far Cry 2",
    "'War…war never changes' – Fallout",
    "'The world fears the inevitable plummet into the abyss. Watch for that moment and when it comes, do not hesitate to leap. It is only when you fall that you learn whether you can fly.' – Dragon Age: Origins",
    "'Most test subjects do experience some cognitive deterioration after a few months in suspension. Now you’ve been under for… quite a lot longer, and it’s not out of the question that you might have a very minor case of serious brain damage. But don’t be alarmed, alright? Although, if you do feel alarmed, try to hold onto that feeling because that is the proper reaction to being told you have brain damage.' – Portal 2",
    "'Nothing is true, everything is permitted.' – Assassin’s Creed franchise",
    "'It’s dangerous to go alone, take this!' – The Legend of Zelda",
    "'I raised you, and loved you, I’ve given you weapons, taught you techniques, endowed you with knowledge. There’s nothing more for me to give you. All that’s left for you to take in my life.' – Metal Gear Solid 3: Snake Eater",
    "'Boss… you were right. It’s not about changing the world. It’s about doing our best to leave the world… the way it is. It’s about respecting the will of others and believing in your own.' – Metal Gear Solid IV: Guns of the Patriots",
    "'Endure and survive.' – The Last of Us",
    "'Praise the sun!' – Dark Souls",
    "'Do you like hurting other people?' – Hotline Miami",
    "'I’ve struggled a long time with survivin’, but no matter what you have to find something to fight for.' – The Last of Us",
    "'Tell me Bats. What are you scared of? Failing to save this cesspool of a city? Not finding the Commissioner in time? Me, in a thong?' – Batman: Arkham Asylum",
    "Federico: 'It is a good life we lead, brother.' Ezio: 'The best. May it never change.' Federico: 'And may it never change us.' – Assassin’s Creed II",
    "'War is where the young and stupid are tricked by the old and bitter into killing each other.' – Grand Theft Auto IV",
    "'Hope is what makes us strong. It is why we are here. It is what we fight with when all else is lost.' – God of War 3",
    "'Stop right there, criminal scum!' – The Elder Scrolls IV: Oblivion",
    "'Hey! Look! Listen! – The Legend of Zelda: Ocarina of Time",
    "'I used to be an adventurer like you until I took an arrow to the knee.' – The Elder Scrolls V: Skyrim",
    "'Do a barrel roll!' – Star Fox 64",
    "'So, I guess I’d become what they wanted me to be, a killer. Some rent-a-clown with a gun who puts holes in other bad guys. Well, that’s what they had paid for, so in the end, that’s what they got. Say what you want about Americans, but we understand capitalism. You buy yourself a product and you get what you pay for, and these chumps had paid for some angry gringo without the sensibilities to know right from wrong. Here I was about to execute this poor bastard like some dime store angel of death, and I realized they were correct, I wouldn’t know right from wrong if one of them was helping the poor and the other was banging my sister…' – Max Payne 3",
    "'A man chooses; a slave obeys.' – Bioshock",
    "'Snake? Snake? SNAKE!' – Metal Gear Solid",
    "'Grass grows, birds fly, the sun shines, and brother, I hurt people.' – Team Fortress 2",
    "'You gave them the one thing that was stolen from them. A chance. A chance to learn. To find love. To live. And in the end what was your reward? You never said. But I think I know: a family.' – Bioshock",
    "'Stay awhile and listen!' – Diablo 2",
    "'Thank you, Mario! But our Princess is in another castle!' – Super Mario",
    "'Good men mean well. We just don’t always end up doing well.' – Dead Space 3",
    "'Why walk when you can ride?' – The Elder Scrolls III: Morrowind",
    "'You have died of dysentery.' – Oregon Trail",
    "'You mustn’t allow yourself to be chained to fate, to be ruled by your genes. Human beings can choose the kind of life that they want to live. What’s important is that you choose life… and then live.' – Metal Gear Solid",
    "'Men are but flesh and blood. They know their doom, but not the hour.' – The Elder Scrolls: Oblivion",
    "'Dreams have a nasty habit of going bad when you’re not looking.' – Max Payne",
    "'Time passes, people move. Like a river’s flow, it never ends. A childish mind will turn to noble ambition.' – The Legend of Zelda: Ocarina of Time",
    "'Right and wrong are not what separate us and our enemies. It’s our different standpoints, our perspectives that separate us. Both sides blame one another. There’s no good or bad side. Just two sides holding different views.' – Final Fantasy VIII",
    "'At the end of the day, as long as there are two people left on the planet, someone is gonna want someone dead.' – Team Fortress 2",
    "'Don’t make a girl a promise if you know you can’t keep it.' – Halo 3",
    "'My past is not a memory. It’s a force at my back. It pushes and steers. I may not always like where it leads me, but like any story, the past needs resolution. What’s past is prologue.' – Metroid: The Other M",
    "'Our world, with its rules of causality, has trained us to be miserly with forgiveness. By forgiving too readily, we can be badly hurt. But if we’ve learned from a mistake and become better for it, shouldn’t we be rewarded for the learning, rather than punished for the mistake?' – Braid",
    "'The thing about happiness is that you only know you had it when it’s gone. I mean, you may think to yourself that you’re happy. But you don’t believe it. You focus on the petty bull ****, or the next job, or whatever. It’s only looking back by comparison with what comes after that you understand, that’s what happiness felt like.' – Fallout 4",
    "'All men dream – but not equally. Those who dream by night, in the dusty recesses of their minds, wake in the day to find that it was vanity… But the dreamers of the day are dangerous men, for they may act their dream with open eyes, to make it possible. This I did.' From T. E. Lawrence’s Seven Pillars of Wisdom – Uncharted 3",
    "'You can’t hide from the Grim Reaper. Especially when he’s got a gun.' – Grim Fandango",
    "'Reliance upon others is a weakness for the strong but strength for the weak. Wisdom and balance lie in knowing your nature over time.' – Thief II",
    "'I like shorts! They’re comfy and easy to wear!' – Pokémon",
    "'What is a drop of rain, compared to the storm? What is a thought, compared to the mind?' – System Shock 2",
    "'I never asked for this' – Deus Ex: Human Revolution",
    "'Only a mind free of impediments is capable of grasping the chaotic beauty of the world.' – Assassin’s Creed",
    "'We are all our own worst enemy. But also, our best teacher.' – Super Street Fighter IV",
    "'What is a man but the sum of his memories? We are the stories we live, the tales we tell ourselves.' – Assassin’s Creed: Revelations",
    "'No matter how dark the night, the morning always comes.' – Final Fantasy X",
    "'The only thing that can defeat power, is more power.' – Resident Evil: Umbrella Chronicles",
    "'A famous explorer once said that the extraordinary is in what we do, not who we are.' – Tomb Raider",
    "'What is bravery, without a dash of recklessness?' – Dark Souls",
    "'Someday you’re bound to lose everything. Everybody around you will be gone.' – Final Fantasy VIII",
    "'Good! Now we can fight as warriors. Hand-to-hand, it is the basis of all combat. Only a fool trusts his life to a weapon.' – Metal Gear Solid",
    "'Are you a bad enough dude to rescue the president?' – Bad Dudes",
    "'You’ve met with a terrible fate, haven’t you?' – The Legend of Zelda: Majora’s Mask",
    "'The truth, Walker, is that you’re here because you wanted to feel like something you’re not: A hero.' – Spec Ops: The Line",
    "Batman: 'You want to know something funny? Even after everything you’ve done, I would have saved you.'",
    "oker: [laughs, coughs] 'that is pretty funny.' – Batman: Arkham City",
    "'Stand in the ashes of a trillion dead souls and ask the ghosts if honor matters. Their silence is your answer.' – Mass Effect 3",
    "'Life isn’t just about passing on your genes. We can leave behind much more than just DNA. Through speech, music, literature, and movies… what we’ve seen, heard, felt… anger, joy, and sorrow… these are the things I will pass on. That’s what I live for. We need to pass the torch, and let our children read our messy and sad history by its light. We have all the magic of the digital age to do that with. The human race will probably come to an end sometime, and new species may rule over this planet. Earth may not be forever, but we still have the responsibility to leave what traces of life we can. Building the future and keeping the past alive are one and the same thing.' – Metal Gear Solid 2: Sons of Liberty",
    "'Did I ever tell you the definition of insanity?' – Far Cry 3",
    "'Force answers force, war breeds war, and death only brings death. To break this vicious circle, one must do more than just act without any thought or doubt.' – Metro 2033",
    "'I got caught up in the money, the power…I don’t give a s**t, oh f**k man…I had no choice, I had to do it…I only see the opportunity. But when I’m gone, everyone’s gonna remember my name: Big Smoke!' – Grand Theft Auto: San Andreas",
    "'Shadow and light are two sides of the same coin. One cannot exist without the other.' – The Legend of Zelda: Twilight Princess",
    "'A hero need not speak. When he is gone, the world will speak for him' – Halo",
    "'DEATH IS A PREFERABLE ALTERNATIVE TO COMMUNISM' – Fallout 3",
    "'…it is merely an observation on the nature of reality. To say that nothing is true is to realize that the foundations of society are fragile and that we must be the shepherds of our civilization. To say that everything is permitted is to understand that we are the architects of our actions and that we must live with our consequences, whether glorious or tragic.' – Assassin’s Creed: Revelations",
    "'It ain’t no secret I didn’t get these scars falling over in church.' – Red Dead Redemption",
    "'What is better – to be born good, or to overcome your evil nature through great effort?' – The Elder Scrolls V: Skyrim",
    "'I am Andrew Ryan, and I’m here to ask you a question. Is a man not entitled to the sweat of his brow? ‘No!’ says the man in Washington, ‘It belongs to the poor.’ ‘No!’ says the man in the Vatican, ‘It belongs to God.’ ‘No!’ says the man in Moscow, ‘It belongs to everyone.’ I rejected those answers; instead, I chose something different. I chose the impossible. I chose… Rapture, a city where the artist would not fear the censor, where the scientist would not be bound by petty morality, Where the great would not be constrained by the small! And with the sweat of your brow, Rapture can become your city as well.' – Bioshock",
    "'No Russian.' – Call of Duty: Modern Warfare 2",
    "'Love is just a chemical. We give it meaning by choice.' – Bioshock 2",
    "'War has changed' – Metal Gear Solid IV",
    "'If our lives are already written, it would take a courageous man to change the script.' – Alan Wake",
    "'There are two ways of arguing with a woman, and neither one works' – Red Dead Redemption",
    "'Had to be me… Someone else might have got it wrong.' – Mass Effect 3",
    "'Waka Waka Waka' – Pacman",
    "'[silence]' – The Legend of Zelda",
    "'Now is the time to choose! Die and be free of pain, or live and fight your sorrow. Now is the time to shape your stories! Your fate is in your hands' – Final Fantasy X",
    "'NOTHING IS MORE BADASS THAN TREATING A WOMAN WITH RESPECT!' – Borderlands 2",
    "'I don’t need a weapon; my friends are my power!' – Kingdom Hearts",
    "'The cake is a lie' – Portal",
    "'You require more vespene gas' and 'Not Enough Minerals' – StarCraft",
    "'Frostmourne hungers' – WarCraft III",
    "'You Have Died' – Dark Souls",
    "'Kept you waiting, huh?' — Metal Gear Solid 5: Ground Zeroes"
];